[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2E2E2E"
textColor = "#FFFFFF"
font = "sans serif"